# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'devopsparambarai(bdd69d62-23b8-4518-a494-53a777eb2d26)'
    subscriptionId: 'bdd69d62-23b8-4518-a494-53a777eb2d26'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'robo'
    location: 'West Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/Vnet1.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Deployvnet2'