# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '2e90ef6b-b015-4284-914f-30032976794d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'sarpettaparambarai'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/Vnet3.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Deployvnet3'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '2e90ef6b-b015-4284-914f-30032976794d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'sarpettaparambarai'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/deepanredhat/Azure_ARM/main/Vnet2.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Deployvnet2'